### PR TITLE
Fix for #14

### PR DESCRIPTION
**Pull request by hryamzik**

### CODE REVIEW

**Comment by brutasse** [comment]
Thanks for this… I've seen this patch in the cyanite repo but I'm reluctant to merge it while cyanite is in flux. This is a workaround more than a fix.

There is some ongoing work in the Cyanite API which should improve the "find paths" story. In the meantime I'm inclined towards telling people who want to use cyanite master *right now* to patch their graphite-cyanite installation. The Cyanite API will be fixed Very Soon™ and it'll be a more solid basis :)

**Comment by pyr** [comment]
Onboard with @brutasse on this.

**Comment by hryamzik** [comment]
Not required any more.

**Comment by brutasse** [comment]
Indeed, thanks!

**Pull request closed without merging**
